name: Linting Test and Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - README.MD
      - readme.md
  pull_request:
    branches: [ main ]

jobs:
  docker-build-and-update-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Run Linting
        run: flake8 --ignore=E501,F401 .
      
      - name: Docker Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          NEW_TAG=v$(date +"%Y%m%d%H%M%S")
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          docker build . -t sanjithmohanan/ghaction:$NEW_TAG 
      
      - name: Push Docker Image
        run: |
          echo "Pushing Docker image with tag: ${{ env.NEW_TAG }}"
          docker push sanjithmohanan/ghaction:${{ env.NEW_TAG }}

      - name: Update Kubernetes manifest files
        run: |          
          sed -i "s|image: sanjithmohanan/ghaction:.*|image: sanjithmohanan/ghaction:${NEW_TAG}|" manifests/deployment.yaml
          echo "---Updated Manifest---"
          cat manifests/deployment.yaml
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add manifests/deployment.yaml
          git commit -m "Update manifest from GitHub Actions [ci skip]"
          git push origin main

        
      